Version: 3.4.1.2340
Installer:
- InstallerUrl: https://muse-cdn.com/Muse_Hub.exe
  InstallerSha256: 4632A0CB0FB926AD9C45250F9E1DDE4D64D46B3456CA3894D4AA2E13F0C17FCC
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Mac (3.3.1)
    - Support for Audacity 4
    Windows (3.4.1)
    See changelog at https://support.musehub.com/en/articles/17327414-windows-changelog
    Linux (2.2.1)
    See changelog at https://support.musehub.com/en/articles/15070607-changelog
ReleaseTime: 2024-06-20T15:48:19.3030000Z
ETag:
- '"51c24780a4d99470c673ce8720fd928e"'
