Version: 1.1.3
Installer:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/241130tqe9q3y/Comfy Desktop Setup 1.1.3 - Build 260925phvzmrjn6-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/Comfy-Org/Comfy-Desktop/releases
ReleaseTime: 2026-09-25T03:17:07.0000000Z
