Version: 10.2.3_1
Installer:
- Architecture: x86
  InstallerUrl: https://web9001.nomachine.com/download/10.2/Windows/nomachine-cloud-server_10.2.3_1_x86.exe
- Architecture: x64
  InstallerUrl: https://web9001.nomachine.com/download/10.2/Windows/nomachine-cloud-server_10.2.3_1_x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://kb.nomachine.com/SU10X00290
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    NoMachine makes available version 10.2.3 to provide a number of enhancements designed to simplify deployment and product activation across the NoMachine product portfolio. Key changes include the renaming of NoMachine Enterprise Client to NoMachine Player, the adoption of a unified subscription model for multi-platform server products and an easier activation procedure for online deployments. This update also includes improvements to certificate handling on Windows and updated OpenSSL libraries to further strengthen security and compatibility.
    NoMachine Enterprise Client is now NoMachine Player
    NoMachine Player is the new name for our free standalone client. Designed for users who only need to run connections to their remote machines, it provides all the features required for remote access without installing the server component on the local machine. Available for download at https://download.nomachine.com/player/, NoMachine Player can be used to connect to any machine running the Personal Edition or an Enterprise product.
    One server subscription for all platforms
    Multi-platform server products now use a single subscription across Windows, macOS, and Linux. Install the package for your preferred OS and activate it with your subscription. If you switch to another supported platform of the same product, the same subscription can be used without requiring a new license.
    Easier activation with a subscription key
    For software subscriptions validated online, server software can now be activated through the user interface using a simple ‘subscription key’ eliminating the need to install the complete server.lic file.
    Changes to the NoMachine Network trial
    The free 7-day NoMachine Network trial is no longer activated automatically when you create an account. To start a trial of this service, users can login to their User Area on the website and manually activate it from the ‘Evaluations’ section.
    Improvements to how CA system certificates are handled
    Additionally, this release makes NoMachine able to use CA system certificates on Windows without the need to specify their path in the "Certificate authority" key in user's player.cfg.
    New OpenSSL libraries
    OpenSSL libraries shipped by NoMachine client and server packages have been updated to v3.5.8 . The full list of CVE patched by the new OpenSSL 3.5.8 is available on their Official web site at: https://openssl-library.org/news/openssl-3.5-notes/
    Updates to the nxhtd component
    The nxhtd component included in commercial server packages is now based on httpd 2.4.69, changes in the new version of Apache are listed here: https://downloads.apache.org/httpd/CHANGES_2.4.69
    Trouble Reports solved in v10.2.3 are:
    TR10X12000 - Uninstalling NoMachine Player on Windows leaves shortcuts after an automatic update from Enterprise Client
    TR08X11948 - The client may ignore the 'DIRECT' setting in the proxy PAC file
    TR09X11973 - Large Kerberos token pass may fail on client side
    TR09X11974 - Rules for the nodes may be not updated properly when upgrading a Cloud Server from v9 to v10
    TR09X11981 - It may be not possible to start virtual sessions on rpm-based distributions with GNOME 49+
    TR09X11984 - Further authentication may not work for inverse nodes running v9/v10 when added to a v8 Cloud Server
    TR09X11976 - The player may terminate while accessing smart cards on Windows
    TR09X11982 - Reconnect procedure may not work for specific users
    TR09X11980 - Possible buffer overflow in Kerberos token parsing on client side
    TR09X11989 - Cross-site scripting (XSS) vulnerability in web sessions may be exploited for code injection
    TR08X11946 - Possible privilege escalation through 'nxservice' on Windows
    TR08X11947 - Possible privilege escalation through 'nxfs' service on Windows
    TR09X11993 - Possible stack-based buffer overflow in the pre-authentication phase (NX protocol)
RealVersion: 10.2.3
ReleaseTime: 2026-10-06
