Version: 0.7.1
Installer:
- InstallerUrl: https://download.crew.kiro.dev/desktop/stable/0.7.1/KiroCrew-Setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotesUrl
  Value: https://github.com/kirodotdev/KiroCrew/releases
ReleaseTime: 2026-09-25T01:22:58.0000000Z
