Version: 156.0.8078.4
Installer:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/deuwfvv47ohw7d6gzan5gbln7i_156.0.8078.4/156.0.8078.4_chrome_installer_uncompressed.exe
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/actf4zlqdczrrkdn753xomj4k3uq_156.0.8078.4/156.0.8078.4_chrome_installer_uncompressed.exe
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/bxdlncyqc2vbtxag32tpwdsyhy_156.0.8078.4/156.0.8078.4_chrome_installer_uncompressed.exe
Locale: []
